### ISSUE TITLE
running as a background process?

### ISSUE THREAD

**Issue by valdimar94** [simonh1000/angular-http-server#6]
I am having trouble running this as a background process for my app. I am currently trying npm forever to run this on a server which I ssh to, and run this command in the angular dist/ directory:
forever start $(angular-http-server -p 1337) .
which starts the process, but wont let me continue using the terminal so I can actually exit the server.
I have tried many variations in an attempt to do this, but nothing has worked so far. This command I listed works for http-server, but that routes the url requests in an undesirable manner(404 not found etc...).

**Comment by greenygh0st** [comment]
That is because it’s running in the foreground. See if you can hit Ctrl+Z and they type bg hit enter. 😄

**Comment by greenygh0st** [comment]
...and then make sure everything is still running. 😄

**Comment by greenygh0st** [comment]
So actually I just tried to do this the way you are and it's not allowing me to suspend the process. My guess is that it has something to do with forever itself. Come to think of it you shouldn't even have to use forever because the server will, in fact, listen forever. You just need it out of the foreground so you can log out. 

If don't have to use forever I would just run the command with nohup:

`nohup angular-http-server -p 1337`

Then again it's the same process, Ctrl+Z and Type bg + enter (to background it).

angular-http-server is running more like a traditional application on your box. I did a test using nohup and that should work for you. If this is to be a production application, in the end, I would strongly recommend using something like Dokku to manage what happens if the box restarts.

Working example:
http://165.227.191.66:1337/

![image](https://user-images.githubusercontent.com/1551020/31079946-f267249a-a74c-11e7-872b-24a3df8f01e9.png)

**Comment by valdimar94** [comment]
This works great! Thank you so much. I will check out Dokku as you suggest, but this issue can be closed @simonh1000.
